### ISSUE TITLE
Update NG Packages/Libraries & Add Docker ENV

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorPhotoAgent.UI#24]
- [x]  1 Update NG Packages & Libraries 

- [x]  2 Add Docker ENV 
APIENDPOINT=https://agent.navigatorglass.com/api/

- [x]  3 Deploy to Docker Hub
https://hub.docker.com/r/stuartshay/navigator-photo-agent-ui/

- [x]  4 Fix GH Pages (Using https)

**Comment by leduong** [comment]
Hi, need the ENV generator again, it is unique for each project

# travis encrypt DOCKER_USERNAME=stuartshay DOCKER_PASSWORD=yourPassword --add env.global

**Comment by stuartshay** [comment]
This Looks Good
