### ISSUE TITLE
Password Recovery - Mock Pages

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorPhotoAgent.UI#41]
Password Recovery Page

![untitled](https://user-images.githubusercontent.com/887805/34239956-f07717d8-e5d8-11e7-91fd-3207dc9dab0f.png)

**Comment by magnastrazh** [comment]
Hi!
We can use link with token instead of step 2 .
https://outBestSite/#recoveryPassword?link=8746F9D81838DB6A43C66C0DD3ED7E9D76E58346
after success redirect to step 3

**Comment by stuartshay** [comment]
Yes, this is a Option and this is worth trying open to sugestions

**Comment by stuartshay** [comment]
This is Good for Now !!!
